### ISSUE TITLE
Código en mal sitio

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twQ103-cartelera-de-cine#1]
El código no debe estar en el readme, debéis subir un archivo al repo del tipo: "cartelera.c" o "main.c" dentro del cual esté el código. 

Aunque no sea la versión definitiva, se recomienda que organicéis bien vuestro repo, si tenéis cualquier duda, comentadlo por aquí o escribidme un correo

**Comment by Juliauru** [comment]
Arreglado!
